const data = [
  {
    id: 1,

    name: 'shoe',
    image: '/images/shoe.webp',
    category: 'shoe',
    description: 'High quality shoe',
    rating: 4.5,
    countInStock: 5,
    numReviews: 4,
  },
  {
    id: 2,

    name: 'laptop',
    image: '/images/laptop.jpg',

    category: 'laptop',
    description: 'High quality laptop',
    rating: 4.5,
    countInStock: 5,
    numReviews: 4,
  },
  {
    id: 3,

    name: 'bicycle',
    image: '/images/bicycle.webp',
    category: 'bicycle',
    description: 'High quality bicycle',
    rating: 4.5,
    countInStock: 5,
    numReviews: 4,
  },
  {
    id: 4,
    name: 'big handbag',
    image: '/images/handbag2.jpg',
    category: 'hand bag',
    description: 'High quality hand bag',
    rating: 4.5,
    countInStock: 5,
    numReviews: 4,
  },
  {
    id: 5,
    name: 'small handbag',
    image: '/images/handbags.webp',
    category: 'hand bag',
    description: 'High quality hand bag',
    rating: 4.5,
    countInStock: 25,
    numReviews: 4,
  },
  {
    id: 6,
    name: 'nivea',
    image: '/images/nivea.png',
    category: 'cream',
    description: 'High quality cream',
    rating: 4.5,
    countInStock: 5,
    numReviews: 4,
  },
  {
    id: 7,
    name: 'speaker',
    image: '/images/speaker.png',
    category: 'Electronics',
    description: 'High quality electronics',
    rating: 4.5,
    countInStock: 5,
    numReviews: 4,
  },
  {
    id: 8,
    name: 'wrist watch',
    image: '/images/wristwatch.webp',
    category: 'electronics',
    description: 'High quality wrist watch',
    rating: 4.5,
    countInStock: 5,
    numReviews: 4,
  },
  {
    id: 9,
    image: '/images/snikkers.webp',
    name: 'Snikker',
    category: 'shots',
    description: 'High quality shot',
    rating: 5,
    countInStock: 7,
    numReviews: 6,
  },
];

module.exports = data;
